# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_charge_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='date',
        ),
    ]
