# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_account_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='finance.Profile'),
        ),
    ]
